output-format: json

strictness: medium
test-warnings: true
doc-warnings: false

ignore-paths:
    - docs
    - venv

# pep8:
#     disable:
#         - W602
#         - W603
#     enable:
#         - W601
#     options:
#         max-line-length: 79

mccabe:
    run: false
