language: python
python:
- 3.9
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  password:
    secure: lZf4qFJv6xuwhtfNwV7QBfsg9r3OnBlrhe5VCBlqR9PpE+xcMT5Gl1Qb8vwCHuWaV+TIUK5qaPN478GlW2qLwM9jm42WBh8QpB87miUR+uNNwBsGhgsfaPg8/rRvTHp+zpWwYGsA/b7edoKanNU7AHNCP4GtPW6HF0RIo7a2IHBzgdjW/9SrQXdAcWIfE8a/0yawofDkbgM/FVUgbt/bAP2Bf4HC/Izq9z5RdfpcZ27yfW0OefkkDKW8RhvkJ6zCqoyvJTkWlyFoiEFkBo6a5nfvHcGeVATuXYGkppa8qpEWgq20rn3Z+uz4eNmamWfx2CmWH0+U5ItNDHrjjvXwaswmEMUeA28m/plffT5tqHnKgxHQnkYKi6V0QlbR1prH6P6SfpnIncelI3+AUCvyNBDaGw3STbCxX7cRdpY4KXfoF2W+deFVV8iS+mPpVQFW8LtFYeI+GP5MyHLc1iF8h9e8Pafz9OkqN8Ab3tEnoEO/3Nl2vmvyjauf0lhIdLBGq5JEiQq/BjSBbGky6M0ZG0BjkW/y8mAzUH0bgiVtWKvi/6Z5I4PSfP4QtE+QlOjlZbh3SuvLT5Yub+IgEBvmua/6OJFlnGHfDiIG7WRCigvQMOeiOsIt7ihMEy62KOJHQfgbSl6TBDZUO2WsnnxGbmS1yFqEnKsxy0sF7Wvq5VU=
  on:
    tags: true
    repo: FranciscoMoretti/py_bipartite_matching
    python: 3.8
