language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: FranciscoMoretti
  password:
    secure: dD0Ff+llXThWtr24BpqP1adRCodnDNVErB9zUoY/iGQnoViASta5a8iRKk0eTwrGRRa6O5yxoWl01H4Bjd4Rhs9HhUDS8sEaCLFyqwq5KrZoBYwYrYkYgACTNlPgX5xKOcy4TWPKAzUWT+XmF8qxH+RZBuyPTMweNrRvWHMSmyjUrdzBmo6+/QledGn1viv4TJ/5jz5Z9pelViz8F4/dXNRa8b/wcvWGXKmvrlNvhELc0IRKcqT737t9RFuP35VCQxBHFhcfI0N+iesggn4lSCFCqsvuXMQcVAHVIlKhZvKAtgsjbqm0Ha+3eh253UZhoOniw6gJber18OqpAK0pOCjGA9Oz5K8yBA5dL6LI3rzKu9BlRQ0mOyLeiYP9hwbxfKnV/0VQR5xuKZA+Hg0r3quSMd1d6l8peQtNPuxdDZ4rG79cK5d3LzMXB/Qe4WSwfT1NKiy1iSSxBL+xkIEYKtaLNfqlu8OWwU7yUHcd97nds80P2VgXFJJYbYetjZFyrTKlSq8FrWSrDC/ji9o0yG4PACyhw96qMaVJYDHkMjO+zkNpS9TO0qDzXckC8lbRRmbQtswM/8txy7bU/f1BPXop+rsuzHJs844X243nefw1I+T0T8oLnAor0N2C22CB8PYUdgZ2dJ/n2M13qEJcSYlypFYeGAl0zjnJcvqeNk4=
  on:
    tags: true
    repo: FranciscoMoretti/py_bipartite_matching
    python: 3.8
